name: run ui test
on:
  push:
    branches:
      - master
  schedule:
    # Runs every hour, stupid delays: https://upptime.js.org/blog/2021/01/22/github-actions-schedule-not-working/
    - cron: '55 * * * *'
    - cron: '56 * * * *'
    - cron: '57 * * * *'
    - cron: '58 * * * *'
    - cron: '59 * * * *'
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  pipeline:
    name: run ui test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install node.js packages
        run: npm install
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 2
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Usage
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME
      - name: Cypress run
        uses: cypress-io/github-action@v2
