name: run ui test
on:
  push:
    branches:
      - master
  schedule:
    # Runs every hour
    - cron: '1 * * * *'
  workflow_dispatch:

jobs:
  pipeline:
    name: run ui test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12.16.1
      - name: Install node.js packages
        run: npm install
      - name: Get Time
        id: time
        uses: nanzm/get-time-action@v1.1
        with:
          timeZone: 2
          format: 'YYYY-MM-DD-HH-mm-ss'
      - name: Usage
        env:
          TIME: "${{ steps.time.outputs.time }}"
        run: |
          echo $TIME
      - name: Cypress run
        uses: cypress-io/github-action@v2
